config/routes.rb
Rails.application.routes.draw do
devise_for :users ,only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}
	scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  		devise_for :users ,skip: :omniauth_callbacks

		resources :manuals do
			resources :comments
			member do
				put "like" => "manuals#vote"
			end
		end
		resources :steps
		resources :tags, only: [:show]
		resources :categories, only: [:show]
  		resources :uploads, only: [:index, :create]
		root 'manuals#index'
		resources :users, only: [:show]
		get "search", to: "search#search"

		namespace :admin do
			resources :categories, except: [:show]	
			resources :users, except: [:show]	
			delete 'user/delete_user', :as => :delete_user
			delete 'user/ban_user', :as => :ban_user
			delete 'user/unban_user', :as => :unban_user
		end

	end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  has_many :manuals
  has_many :steps
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable, :omniauthable

  devise :omniauthable, :omniauth_providers => [:facebook, :vkontakte]

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  
  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_create do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.username = auth.info.nickname
  	end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  
  def index
    @users = User.all
  end
  
  def desroy 
    User.find(params[:id]).destroy
    redirect_to admin_users_url
  end

  def update
    @user = User.find(params[:id])
    @user.update(blocked: !@user.blocked)
    redirect_to admin_users_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def banned(user)
		user.blocked ? t('.unban'):	t('.ban')
	end
	def ban_class(user)
		user.blocked ? "success" :	'danger'
	end
end

app/views/users/show.html.erb
<h1><%= t('.users_man') %></h1>

<div class="buttons_panel">
	<%= link_to t('.new_man'), new_manual_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th><%= t('.title') %></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @user.manuals.each_with_index do |manual, index| %>
			<tr>
				<td><%= index + 1 %></td>
				<td><%= link_to manual.title, manual_path %></td>
				<td>
					<%= link_to t('.edit'), edit_manual_path(manual), class: 'btn btn-outline-primary btn-sm' %>
					<%= link_to t('.delete'), manual_path(manual), method: :delete, data: {confirm: 'Are you shure?'}, class: 'btn btn-outline-danger btn-sm' %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</section>