config/routes.rb
Rails.application.routes.draw do
devise_for :users ,only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}
	scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  		devise_for :users ,skip: :omniauth_callbacks

		resources :manuals do
			resources :comments
			member do
				put "like" => "manuals#vote"
			end
		end
		resources :steps
		resources :tags, only: [:show]
		resources :categories, only: [:show]
  		resources :uploads, only: [:index, :create]
		root 'manuals#index'
		resources :users, only: [:show]
		get "search", to: "search#search"

		namespace :admin do
			resources :categories, except: [:show]	
			resources :users, except: [:show]	
			delete 'user/delete_user', :as => :delete_user
			delete 'user/ban_user', :as => :ban_user
			delete 'user/unban_user', :as => :unban_user
		end

	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :manuals
	validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
	before_action :set_category, only: [:edit, :update, :destroy]

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to admin_categories_path, success: 'Category has been successfuly created!'
		else
			flash.now[:danger] = 'Category has not been created!'
			render :new
		end
	end

	def edit
	end

	def update
		if @category.update_attributes(category_params)
			redirect_to admin_categories_path, success: 'Category has been succesfuly updated!'
		else
			flash.now[:danger] = 'Category has not been updated!'			
			render :edit
		end
	end

	def destroy
		@category.destroy
		redirect_to admin_categories_path, success: 'Category has been succesfuly deleted!'
	end



	private

	def set_category
		@category = Category.find(params[:id])
	end

	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :set_category, only: [:show]

	def show
		@manuals = @category.manuals.order("created_at DESC").include(:category)
	end

	private

	def set_category
		@category = Category.find(params[:id])
	end
end

app/views/admin/categories/_form.html.erb
<% if @category.errors.any? %>
	<div class="alert alert-danger">
		<h5><%= t('common.errors') %></h5>
		<ul>
			<% @category.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>


<%= form_for [:admin, @category] do |f| %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.submit t('.submit', action: @category.new_record? ? t('common.create') : t('common.edit')), class: 'btn btn-primary' %>
		<%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
	</div>

<% end %>

app/views/admin/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h1><%= t('.title') %></h1>

<div class="buttons_panel">
	<%= link_to t('.new_category'), new_admin_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th><%= t('.name') %></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @categories.each_with_index do |category, index| %>
			<tr>
				<td><%= index + 1 %></td>
				<td><%= category.try :name %></td>
				<td>
					<%= link_to t('.edit'), edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
					<%= link_to t('.delete'), admin_category_path(category), method: :delete, data: {confirm: 'Are you shure?'}, class: 'btn btn-outline-danger btn-sm' %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</section>

app/views/admin/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>