config/routes.rb
Rails.application.routes.draw do
devise_for :users ,only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}
	scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  		devise_for :users ,skip: :omniauth_callbacks

		resources :manuals do
			resources :comments
			member do
				put "like" => "manuals#vote"
			end
		end
		resources :steps
		resources :tags, only: [:show]
		resources :categories, only: [:show]
  		resources :uploads, only: [:index, :create]
		root 'manuals#index'
		resources :users, only: [:show]
		get "search", to: "search#search"

		namespace :admin do
			resources :categories, except: [:show]	
			resources :users, except: [:show]	
			delete 'user/delete_user', :as => :delete_user
			delete 'user/ban_user', :as => :ban_user
			delete 'user/unban_user', :as => :unban_user
		end

	end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Manual
    can :read, Comment  
    can :read, Category
    if user.present?  
      can :manage, Manual, user_id: user.id 
      can :manage, Comment, user_id: user.id 
      can :read, Category
      if user.admin?  
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :manuals
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to	:manual

	validates :body, presence: true
	after_create_commit { RenderCommentJob.perform_later self}
end

app/models/manual.rb
require 'elasticsearch/model'

class Manual < ApplicationRecord
	acts_as_votable
	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks


	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings

	has_many :steps, dependent: :destroy
	accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true

	has_many :comments, dependent: :destroy
	belongs_to :category
	belongs_to :user

	has_attached_file :image, styles: { small: "64x64", thumb: "200x200", large: "650x650" }
	validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

	validates :title, presence: true
	validates :summary, presence: true
	validates :body, presence: true

	def all_tags
		self.tags.map(&:name).join(' #')
	end

	def all_tags=(names)
		self.tags = names.split('#').map do |name|
			Tag.where(name: name.strip).first_or_create!
		end
	end


	def self.search(query)
	  __elasticsearch__.search(
	    {
	      query: {
	        multi_match: {
	          query: query,
	          fields: ['title','summary', 'body']
	        }
	      },
	      highlight: {
	        pre_tags: ['<em>'],
	        post_tags: ['</em>'],
	        fields: {
	          title: {},
	          text: {}
	        }
	      }
	    }
	  )
	end
end

app/models/step.rb
class Step < ApplicationRecord
	belongs_to :manual, optional: true
	belongs_to :user

	has_attached_file :image, styles: {thumb: "400x400", large: "650x650"}
	validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
    validates :title, presence: true    
    validates :body, presence: true

    def self.search(query)
	  __elasticsearch__.search(
	    {
	      query: {
	        multi_match: {
	          query: query,
	          fields: ['title', 'body']
	        }
	      },
	      highlight: {
	        pre_tags: ['<em>'],
	        post_tags: ['</em>'],
	        fields: {
	          title: {},
	          text: {}
	        }
	      }
	    }
	  )
	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	
	has_many :taggings
	has_many :manuals, through: :taggings

	def self.counts
		self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end
	
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :manual
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  has_many :manuals
  has_many :steps
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable, :omniauthable

  devise :omniauthable, :omniauth_providers => [:facebook, :vkontakte]

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  
  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_create do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.username = auth.info.nickname
  	end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:term].nil?
      @manuals = []
    else
      @manuals = Manual.search params[:term]
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
	def destroy
		@step = Step.find(params[:id])
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by(name: params[:id]).include(:name)
		@manuals = @tag.manuals.order("created_at DESC")
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygment < Redcarpet::Render::HTML
		def block_code(code,language)
			Pygments.highlight(code, lexer: language)
		end
	end

	def bootstrap_class_for(name)
		{
			success: "alert-success",
			error: "alert-danger",
			danger: "alert-danger",
			alert: "alert-warnint",
			notice: "alert-info"
		}[name.to_sym] || name
	end

	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size-1)
			yield(tag, classes[index.round])
		end
	end

	def category_menu
		categories = Category.all
		categories.each do |category|
			yield(category)
		end
	end

	def markdown(content)
		renderer = HTMLwithPygment.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/image_contents_helper.rb
module ImageContentsHelper
end

app/helpers/manuals_helper.rb
module ManualsHelper

	def category_show(manual)
		if manual.category.present?
			link_to manual.category.name, manual.category, class: "badge badge-info" 
		end 
	end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
	def manuals_for_tags(manual)
		if manual.empty? 
			"<h2>No manuals with this tag</h2>".html_safe
		else 
			render manual
		end 
	end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def banned(user)
		user.blocked ? t('.unban'):	t('.ban')
	end
	def ban_class(user)
		user.blocked ? "success" :	'danger'
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<div class="container sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-lable="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <%= link_to t(:man), manuals_path, class: 'nav-link' %>
        </li>

    </ul>
    
    <div class="mr-auto">
      <%= render 'search/form' %>
    </div>

    <ul class="navbar-nav pull-xs-right">
      <% if user_signed_in? %>
        
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.username %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to t(:my_man),  user_path(current_user.id), class: 'dropdown-item' %>
            <%= link_to t(:new_man),  new_manual_path, class: 'dropdown-item' %>
            <%= link_to t(:all_users),  admin_users_path, class: 'dropdown-item' if current_user.admin? %>
            <%= link_to t(:categ),  admin_categories_path, class: 'dropdown-item' if current_user.admin? %>
          <div class="dropdown-divider"></div>
            <%= link_to t(:sign_out), destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>

      <% else %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t(:sign_in) %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "FB", user_facebook_omniauth_authorize_path, class: 'dropdown-item' %>
            <%= link_to "VK", user_vkontakte_omniauth_authorize_path, class: 'dropdown-item' %>
            <%= link_to t(:sign_in),  new_user_session_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
            <%= link_to t(:registration), new_user_registration_path, class: 'dropdown-item' %>
        </div>
      </li>

      <% end %>
    </ul>

    <ul class="navbar-nav pull-xs-right">
      <li class="nav-item <%= "active" if I18n.locale == :ru %>">
        <%= link_to 'Рус', {locale: :ru}, class: "nav-link" %>
      </li>
      <li class="nav-item <%= "active" if I18n.locale == :en %>">
        <%= link_to 'En', {locale: :en}, class: "nav-link" %>
      </li>
    </ul>

  </div>
</nav>
</div>
    
    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name,message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">
          <%= yield %>
        </div>
        <div class="col-md-3">
          <h1><%= t(:category) %></h1>
          <nav class="navbar" id="category">
              <ul class="nav nav-pills flex-column">
                <% category_menu do |category| %>
                <li class="nav-item">
                  <%= link_to category.name, category_path(category), class: "nav-link #{'active' if current_page?(category_path(category))}", id:"category-element" %>
                </li>
                <% end %>
              </ul>
          </nav>
  
          <h1><%= t(:tags) %></h1>
          <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class|%>
            <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
        </div>
      </div>

      
    
    </div>
  </body>
</html>